# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\naxonfx.llm\"\x1a\n\nAskRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\".\n\x0b\x41skResponse\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x10\n\x08\x61nswered\x18\x02 \x01(\x08\x32\x44\n\nLLMService\x12\x36\n\x03\x41sk\x12\x16.axonfx.llm.AskRequest\x1a\x17.axonfx.llm.AskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASKREQUEST']._serialized_start=25
  _globals['_ASKREQUEST']._serialized_end=51
  _globals['_ASKRESPONSE']._serialized_start=53
  _globals['_ASKRESPONSE']._serialized_end=99
  _globals['_LLMSERVICE']._serialized_start=101
  _globals['_LLMSERVICE']._serialized_end=169
# @@protoc_insertion_point(module_scope)