# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from llm_node import llm_pb2 as llm__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub:
    """LLMService is a standalone, independent node - it holds no replicated
    state, and does NOT talk to the AxonFx Raft cluster at all. It
    answers general questions about how AxonFx works, grounded in a
    static FAQ.md, using a local LLM (see llm_node/llm_api.py). It
    cannot submit transfers and cannot read live balances or transfer
    history - use client/cli.py directly for either of those.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ask = channel.unary_unary(
                '/axonfx.llm.LLMService/Ask',
                request_serializer=llm__pb2.AskRequest.SerializeToString,
                response_deserializer=llm__pb2.AskResponse.FromString,
                _registered_method=True)


class LLMServiceServicer:
    """LLMService is a standalone, independent node - it holds no replicated
    state, and does NOT talk to the AxonFx Raft cluster at all. It
    answers general questions about how AxonFx works, grounded in a
    static FAQ.md, using a local LLM (see llm_node/llm_api.py). It
    cannot submit transfers and cannot read live balances or transfer
    history - use client/cli.py directly for either of those.
    """

    def Ask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ask': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=llm__pb2.AskRequest.FromString,
                    response_serializer=llm__pb2.AskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'axonfx.llm.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('axonfx.llm.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService:
    """LLMService is a standalone, independent node - it holds no replicated
    state, and does NOT talk to the AxonFx Raft cluster at all. It
    answers general questions about how AxonFx works, grounded in a
    static FAQ.md, using a local LLM (see llm_node/llm_api.py). It
    cannot submit transfers and cannot read live balances or transfer
    history - use client/cli.py directly for either of those.
    """

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axonfx.llm.LLMService/Ask',
            llm__pb2.AskRequest.SerializeToString,
            llm__pb2.AskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


