# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from axonfx_node import exchange_pb2 as exchange__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in exchange_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientServiceStub:
    """ClientService is the ONLY interface external clients talk to.
    Raft/consensus internals (handled by pysyncobj) are not exposed here -
    a client can call any node in the cluster and get a correct answer.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTransfer = channel.unary_unary(
                '/axonfx.ClientService/SubmitTransfer',
                request_serializer=exchange__pb2.SubmitTransferRequest.SerializeToString,
                response_deserializer=exchange__pb2.SubmitTransferResponse.FromString,
                _registered_method=True)
        self.GetBalances = channel.unary_unary(
                '/axonfx.ClientService/GetBalances',
                request_serializer=exchange__pb2.GetBalancesRequest.SerializeToString,
                response_deserializer=exchange__pb2.GetBalancesResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/axonfx.ClientService/GetStatus',
                request_serializer=exchange__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=exchange__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.GetTransferHistory = channel.unary_unary(
                '/axonfx.ClientService/GetTransferHistory',
                request_serializer=exchange__pb2.GetHistoryRequest.SerializeToString,
                response_deserializer=exchange__pb2.GetHistoryResponse.FromString,
                _registered_method=True)


class ClientServiceServicer:
    """ClientService is the ONLY interface external clients talk to.
    Raft/consensus internals (handled by pysyncobj) are not exposed here -
    a client can call any node in the cluster and get a correct answer.
    """

    def SubmitTransfer(self, request, context):
        """Submit a cross-border transfer. Blocks until the transfer has been
        committed by a majority of the Raft cluster and fully settled.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalances(self, request, context):
        """Read-only balance lookup (served locally, no need to hit the leader -
        reads are allowed to be slightly stale on followers, which is fine for
        a "check my liquidity pools" style query).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Cluster/node health & Raft role, useful for demos ("who is leader now").
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransferHistory(self, request, context):
        """Transfer history (for demo/debugging visibility into what happened).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTransfer,
                    request_deserializer=exchange__pb2.SubmitTransferRequest.FromString,
                    response_serializer=exchange__pb2.SubmitTransferResponse.SerializeToString,
            ),
            'GetBalances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalances,
                    request_deserializer=exchange__pb2.GetBalancesRequest.FromString,
                    response_serializer=exchange__pb2.GetBalancesResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=exchange__pb2.GetStatusRequest.FromString,
                    response_serializer=exchange__pb2.GetStatusResponse.SerializeToString,
            ),
            'GetTransferHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransferHistory,
                    request_deserializer=exchange__pb2.GetHistoryRequest.FromString,
                    response_serializer=exchange__pb2.GetHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'axonfx.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('axonfx.ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService:
    """ClientService is the ONLY interface external clients talk to.
    Raft/consensus internals (handled by pysyncobj) are not exposed here -
    a client can call any node in the cluster and get a correct answer.
    """

    @staticmethod
    def SubmitTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axonfx.ClientService/SubmitTransfer',
            exchange__pb2.SubmitTransferRequest.SerializeToString,
            exchange__pb2.SubmitTransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axonfx.ClientService/GetBalances',
            exchange__pb2.GetBalancesRequest.SerializeToString,
            exchange__pb2.GetBalancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axonfx.ClientService/GetStatus',
            exchange__pb2.GetStatusRequest.SerializeToString,
            exchange__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransferHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axonfx.ClientService/GetTransferHistory',
            exchange__pb2.GetHistoryRequest.SerializeToString,
            exchange__pb2.GetHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
