# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from axonfx_node import raft_pb2 as raft__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in axonfx_node/raft_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RaftServiceStub:
    """The two required consensus RPCs, as actual gRPC calls - this is the wire
    protocol the raft cluster nodes use to talk to each other. Intentionally
    separate from exchange.proto (the client-facing API): this file is
    internal cluster traffic only, never called by a client.

    Field names below match the Raft paper's own RPC signatures (Figure 2)
    as closely as protobuf allows: candidateId/leaderId identify the caller
    on a *request*, exactly as the paper defines them. Replies don't repeat
    the sender's id - a gRPC reply already only ever goes back to whoever
    placed the call, so there's nothing to look up.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/axonfx.raft.RaftService/RequestVote',
                request_serializer=raft__pb2.RequestVoteRequest.SerializeToString,
                response_deserializer=raft__pb2.RequestVoteReply.FromString,
                _registered_method=True)
        self.AppendEntries = channel.unary_unary(
                '/axonfx.raft.RaftService/AppendEntries',
                request_serializer=raft__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=raft__pb2.AppendEntriesReply.FromString,
                _registered_method=True)


class RaftServiceServicer:
    """The two required consensus RPCs, as actual gRPC calls - this is the wire
    protocol the raft cluster nodes use to talk to each other. Intentionally
    separate from exchange.proto (the client-facing API): this file is
    internal cluster traffic only, never called by a client.

    Field names below match the Raft paper's own RPC signatures (Figure 2)
    as closely as protobuf allows: candidateId/leaderId identify the caller
    on a *request*, exactly as the paper defines them. Replies don't repeat
    the sender's id - a gRPC reply already only ever goes back to whoever
    placed the call, so there's nothing to look up.
    """

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=raft__pb2.RequestVoteRequest.FromString,
                    response_serializer=raft__pb2.RequestVoteReply.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=raft__pb2.AppendEntriesRequest.FromString,
                    response_serializer=raft__pb2.AppendEntriesReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'axonfx.raft.RaftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('axonfx.raft.RaftService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RaftService:
    """The two required consensus RPCs, as actual gRPC calls - this is the wire
    protocol the raft cluster nodes use to talk to each other. Intentionally
    separate from exchange.proto (the client-facing API): this file is
    internal cluster traffic only, never called by a client.

    Field names below match the Raft paper's own RPC signatures (Figure 2)
    as closely as protobuf allows: candidateId/leaderId identify the caller
    on a *request*, exactly as the paper defines them. Replies don't repeat
    the sender's id - a gRPC reply already only ever goes back to whoever
    placed the call, so there's nothing to look up.
    """

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axonfx.raft.RaftService/RequestVote',
            raft__pb2.RequestVoteRequest.SerializeToString,
            raft__pb2.RequestVoteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axonfx.raft.RaftService/AppendEntries',
            raft__pb2.AppendEntriesRequest.SerializeToString,
            raft__pb2.AppendEntriesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
