# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: axonfx_node/raft.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'axonfx_node/raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61xonfx_node/raft.proto\x12\x0b\x61xonfx.raft\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12\x15\n\rlast_log_term\x18\x04 \x01(\x03\"6\n\x10RequestVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"8\n\x08LogEntry\x12\r\n\x05index\x18\x01 \x01(\x03\x12\x0c\n\x04term\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\x0c\"\x9c\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x12\n\nprev_index\x18\x03 \x01(\x03\x12\x11\n\tprev_term\x18\x04 \x01(\x03\x12\x14\n\x0c\x63ommit_index\x18\x05 \x01(\x03\x12&\n\x07\x65ntries\x18\x06 \x03(\x0b\x32\x15.axonfx.raft.LogEntry\"O\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x16\n\x0e\x65ntry_appended\x18\x02 \x01(\x08\x12\x13\n\x0bmatch_index\x18\x03 \x01(\x03\x32\xb1\x01\n\x0bRaftService\x12M\n\x0bRequestVote\x12\x1f.axonfx.raft.RequestVoteRequest\x1a\x1d.axonfx.raft.RequestVoteReply\x12S\n\rAppendEntries\x12!.axonfx.raft.AppendEntriesRequest\x1a\x1f.axonfx.raft.AppendEntriesReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'axonfx_node.raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTVOTEREQUEST']._serialized_start=39
  _globals['_REQUESTVOTEREQUEST']._serialized_end=142
  _globals['_REQUESTVOTEREPLY']._serialized_start=144
  _globals['_REQUESTVOTEREPLY']._serialized_end=198
  _globals['_LOGENTRY']._serialized_start=200
  _globals['_LOGENTRY']._serialized_end=256
  _globals['_APPENDENTRIESREQUEST']._serialized_start=259
  _globals['_APPENDENTRIESREQUEST']._serialized_end=415
  _globals['_APPENDENTRIESREPLY']._serialized_start=417
  _globals['_APPENDENTRIESREPLY']._serialized_end=496
  _globals['_RAFTSERVICE']._serialized_start=499
  _globals['_RAFTSERVICE']._serialized_end=676
# @@protoc_insertion_point(module_scope)
